server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心动态创建路由的功能,利用微服务名进行路由
      routes:
        - id: payment_routh #路由id,没有固定规则但要求唯一
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/** #断言,路径相匹配的进行路由


            #- Header=X-Request-Id,\d+ #请求头要为X-Request-Id而且请求数据必须是整数的正则表达式
            #- Method=GET
            #- Cookie=username,11496
            #- Between=2020-06-06T14:12:28.896+08:00[Asia/Shanghai],2020-06-06T19:12:28.896+08:00[Asia/Shanghai]
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka