server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    #是否自己注册自己
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #defaultZone: http://eureka7002.com:7002/eureka/
      #单机模式
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    #关闭自我保护
    enable-self-preservation: false
    #只允许断链2s
    eviction-interval-timer-in-ms: 2000